[package]
name = "pi_vm"
version = "0.1.0"
authors = ["zuon <dev@dev.com>"]

[dependencies]
fnv = "*"
time = "*"
libc = "*"
rand = "*"
magnetic = "*"
threadpool = "*"
lazy_static = "*"
kernel32-sys = "*"

pi_lib = { path = "../pi_lib" }